2021-06-20 23:31:50,286 ERROR: Exception on /index [GET] [in /Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/user/Desktop/microblog/app/routes.py", line 32, in index
    prev_url=prev_url)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/user/Desktop/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/user/Desktop/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/user/Desktop/microblog/app/templates/index.html", line 10, in block "content"
    {% include '_post.html' %}
  File "/Users/user/Desktop/microblog/app/templates/_post.html", line 14, in top-level template code
    <p><a href="{{ url_for('delete_post') }}">Delete Post</a></p>
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'delete_post'. Did you forget to specify values ['post_id']?
2021-06-20 23:33:10,729 INFO: Microblog startup [in /Users/user/Desktop/microblog/app/__init__.py:53]
2021-06-20 23:33:14,206 ERROR: Exception on /index [GET] [in /Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/user/Desktop/microblog/app/routes.py", line 32, in index
    prev_url=prev_url)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/user/Desktop/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/user/Desktop/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/user/Desktop/microblog/app/templates/index.html", line 10, in block "content"
    {% include '_post.html' %}
  File "/Users/user/Desktop/microblog/app/templates/_post.html", line 14, in top-level template code
    <p><a href="{{ url_for('delete_post') }}">Delete Post</a></p>
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/user/Desktop/microblog/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'delete_post'. Did you forget to specify values ['post_id']?
